module.exports = symptomDiseaseMap = {
    fever: ["Flu", "Common Cold", "COVID-19", "Malaria", "Typhoid", "Dengue", "Pneumonia", "Sepsis"],
    cough: ["Bronchitis", "Common Cold", "COVID-19", "Asthma", "Tuberculosis", "Allergic Rhinitis", "Pneumonia"],
    headache: ["Migraine", "Tension Headache", "Flu", "Sinusitis", "Cluster Headache", "Hypertension", "Brain Tumor"],
    sorethroat: ["Strep Throat", "Common Cold", "Tonsillitis", "Influenza", "Pharyngitis", "Mononucleosis"],
    fatigue: ["Anemia", "Diabetes", "Depression", "Hypothyroidism", "Sleep Apnea", "Chronic Fatigue Syndrome", "Cancer"],
    shortnessofbreath: ["Asthma", "COPD", "Heart Failure", "Pneumonia", "Pulmonary Embolism", "COVID-19", "Anemia"],
    chestpain: ["Heart Attack", "Angina", "Pleurisy", "GERD", "Pulmonary Embolism", "Costochondritis"],
    nausea: ["Gastritis", "Food Poisoning", "Pregnancy", "Stomach Flu", "Migraine", "Gallbladder Disease"],
    vomiting: ["Food Poisoning", "Gastritis", "Migraine", "Appendicitis", "Pregnancy", "Gallstones"],
    diarrhea: ["Food Poisoning", "Gastroenteritis", "Irritable Bowel Syndrome", "Cholera", "Crohn's Disease"],
    constipation: ["Irritable Bowel Syndrome", "Hypothyroidism", "Dehydration", "Colon Cancer", "Medication Side Effect"],
    dizziness: ["Vertigo", "Anemia", "Low Blood Pressure", "Dehydration", "Hypoglycemia", "Ear Infection"],
    runnynose: ["Allergic Rhinitis", "Common Cold", "Sinus Infection", "Flu", "COVID-19"],
    stuffynose: ["Sinusitis", "Common Cold", "Allergies", "Nasal Polyps"],
    jointpain: ["Arthritis", "Lupus", "Gout", "Rheumatoid Arthritis", "Lyme Disease"],
    musclepain: ["Influenza", "Fibromyalgia", "Muscle Strain", "Polymyalgia Rheumatica", "Viral Infection"],
    weightloss: ["Diabetes", "Cancer", "Hyperthyroidism", "Malabsorption", "HIV/AIDS"],
    weightgain: ["Hypothyroidism", "Cushing's Syndrome", "PCOS", "Heart Failure", "Depression"],
    rash: ["Eczema", "Psoriasis", "Allergic Reaction", "Chickenpox", "Lupus", "Scabies"],
    itchyeyes: ["Allergies", "Conjunctivitis", "Dry Eyes", "Blepharitis"],
    blurredvision: ["Diabetes", "Glaucoma", "Cataract", "Eye Strain", "Macular Degeneration"],
    chesttightness: ["Asthma", "Panic Attack", "Heart Attack", "COPD"],
    nightsweats: ["Tuberculosis", "Lymphoma", "Menopause", "Hyperthyroidism", "HIV/AIDS"],
    chills: ["Flu", "Malaria", "Pneumonia", "Sepsis", "Urinary Tract Infection"],
    frequenturination: ["Diabetes", "Urinary Tract Infection (UTI)", "Prostate Issues", "Kidney Disease"],
    burningurination: ["UTI", "Kidney Stones", "Prostatitis", "Bladder Infection"],
    backpain: ["Herniated Disc", "Muscle Strain", "Kidney Infection", "Osteoarthritis", "Sciatica"],
    abdominalpain: ["Appendicitis", "Gallstones", "Gastritis", "Pancreatitis", "Ulcer"],
    chestcongestion: ["Bronchitis", "Pneumonia", "Common Cold", "COPD"],
    palpitations: ["Arrhythmia", "Anxiety", "Hyperthyroidism", "Heart Disease", "Electrolyte Imbalance"],
    swollenlymphnodes: ["Infection", "Lymphoma", "Leukemia", "Mononucleosis"],
    soremuscles: ["Flu", "Fibromyalgia", "Overexertion", "Vitamin D Deficiency"],
    trembling: ["Anxiety", "Parkinson's Disease", "Hyperthyroidism", "Hypoglycemia"],
    drymouth: ["Diabetes", "Dehydration", "Sjogren's Syndrome", "Medication Side Effect"],
    excessivethirst: ["Diabetes", "Dehydration", "High Sodium Levels"],
    chestburning: ["GERD", "Acid Reflux", "Peptic Ulcer"],
    earpain: ["Ear Infection", "Sinus Infection", "TMJ Disorder"],
    hearingloss: ["Earwax Blockage", "Ear Infection", "Age-Related Hearing Loss"],
    ringinginEars: ["Tinnitus", "Ear Damage", "High Blood Pressure"],
    sensitivitytolight: ["Migraine", "Meningitis", "Eye Infection"],
    redeyes: ["Conjunctivitis", "Blepharitis", "Glaucoma", "Allergies"],
    itchyskin: ["Allergy", "Eczema", "Liver Disease", "Psoriasis"],
    swellinglegs: ["Heart Failure", "Kidney Disease", "Liver Disease", "Deep Vein Thrombosis"],
    yellowskin: ["Jaundice", "Liver Disease", "Hepatitis"],
    bluelips: ["Hypoxia", "COPD", "Heart Disease"],
    dryskin: ["Eczema", "Dehydration", "Hypothyroidism", "Diabetes"],
    acne: ["Hormonal Imbalance", "PCOS", "Stress", "Oily Skin"],
    brittlenails: ["Iron Deficiency", "Hypothyroidism", "Malnutrition"],
    hairloss: ["Alopecia", "Thyroid Disorder", "Iron Deficiency", "Stress"],
    fainting: ["Low Blood Pressure", "Dehydration", "Heart Condition", "Seizure Disorder"],
    memoryloss: ["Alzheimer's", "Dementia", "Vitamin B12 Deficiency", "Stroke"],
    difficultysleeping: ["Insomnia", "Anxiety", "Sleep Apnea", "Depression"],
    excessivesleep: ["Sleep Apnea", "Depression", "Hypothyroidism", "Narcolepsy"],
    irritability: ["Stress", "Depression", "Hormonal Imbalance", "Sleep Deprivation"],
    swollenfeet: ["Heart Failure", "Kidney Disease", "Liver Cirrhosis", "Varicose Veins"]
};
